name: color_extraction_result
on: [push]
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: color extraction result
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python scripts/save_color_df.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          echo "### Color Dominance Extracted From Image" > report.md
          cat scripts/sample/result.txt >> report.md
          echo "### Sample Image" >> report.md
          cml-publish scripts/sample/_preview.png --md >> report.md
          cml-send-comment report.md